# Generated by Django 4.2 on 2023-12-10 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    def create_room_booking_models(apps, schema_manager):
        """
        Creates the room booking models table.
        """
        apps.create_model('api_room', 'Room', (
            'id', models.AutoField(primary_key=True),
            'name', models.CharField(max_length=100),
            'xona', models.IntegerField(),
            'booked', models.BooleanField(default=False),
            'start', models.DateTimeField(null=True, blank=True),
            'end', models.DateTimeField(null=True, blank=True)
        ))
